### ISSUE TITLE
Initialization started to fail

### ISSUE THREAD

**Issue by vlado48** [Rem0o/FanControl.ADLX#33]
**Describe the bug**
Init started to fail. With both 186 and 185 while working for about 2 weeks without problems. No changes to system except win update afaik. Tried reinstall and system restarts - not helping.

**log**
4/9/2024 9:21:21 PM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
4/9/2024 9:21:21 PM: Initialization failed.
4/9/2024 9:25:41 PM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
4/9/2024 9:25:41 PM: Initialization failed.
4/10/2024 8:05:21 AM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
4/10/2024 8:05:21 AM: Initialization failed.
4/10/2024 8:44:16 PM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
4/10/2024 8:44:16 PM: Initialization failed.

**Relevant hardware specs and setup**
Win 10 - had update approximately of time this started to show up

**Comment by vlado48** [comment]
Thank you for the clarification!
