### ISSUE TITLE
0.3 crashes on startup

### ISSUE THREAD

**Issue by K900** [Rem0o/FanControl.ADLX#45]
Backtrace from Windows logs:

```
Application: FanControl.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at ADLXWrapper.Bindings.ADLXPINVOKE.ADLXHelper_GetLatestMetricsFromTracking(System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, ADLXWrapper.GPUMetricsStruct ByRef)
   at ADLXWrapper.Bindings.ADLXPINVOKE.ADLXHelper_GetLatestMetricsFromTracking(System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, ADLXWrapper.GPUMetricsStruct ByRef)
   at ADLXWrapper.Bindings.ADLXHelper.GetLatestMetricsFromTracking(ADLXWrapper.Bindings.IADLXPerformanceMonitoringServices, ADLXWrapper.Bindings.IADLXGPU, ADLXWrapper.GPUMetricsStruct ByRef)
   at ADLXWrapper.PerformanceMonitor.GetGPUMetricsStructFromTracking(ADLXWrapper.GPU)
   at FanControl.ADLX.GPUMetricsProvider.UpdateMetrics()
   at FanControl.ADLX.GPUMetricsProvider..ctor(ADLXWrapper.PerformanceMonitor, ADLXWrapper.GPU)
   at FanControl.ADLX.ADLXPlugin.<Initialize>b__16_3(ADLXWrapper.GPU)
   at System.Linq.Enumerable+SelectListIterator`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Fill(System.ReadOnlySpan`1<System.__Canon>, System.Span`1<System.__Canon>, System.Func`2<System.__Canon,System.__Canon>)
   at System.Linq.Enumerable+SelectListIterator`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
   at FanControl.ADLX.ADLXPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Bootstrap+<Startup>d__16.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[FanControl.Bootstrap+<Startup>d__16, FanControl, Version=191.0.0.0, Culture=neutral, PublicKeyToken=null]](<Startup>d__16 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[FanControl.Bootstrap+<Startup>d__16, FanControl, Version=191.0.0.0, Culture=neutral, PublicKeyToken=null]](<Startup>d__16 ByRef)
   at FanControl.Bootstrap.Startup(System.Windows.StartupEventArgs)
   at FanControl.App+<OnStartup>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[FanControl.App+<OnStartup>d__3, FanControl, Version=191.0.0.0, Culture=neutral, PublicKeyToken=null]](<OnStartup>d__3 ByRef)
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[FanControl.App+<OnStartup>d__3, FanControl, Version=191.0.0.0, Culture=neutral, PublicKeyToken=null]](<OnStartup>d__3 ByRef)
   at FanControl.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at FanControl.App.Main()
```

Probably needs a check here: https://github.com/Rem0o/ADLX/blob/2ffc8d50c8690da2ef954072d96d78111c868177/SDK/ADLXHelper/Windows/Cpp/ADLXHelper.cpp#L145

And also here: https://github.com/Rem0o/ADLX/blob/2ffc8d50c8690da2ef954072d96d78111c868177/SDK/ADLXHelper/Windows/Cpp/ADLXHelper.cpp#L149

As both of those can fail and return a null pointer.

**Comment by Rem0o** [comment]
You are right those should check the ADLX_RESULT before attempting to access the memory location.  Will do. 

However I find it odd it doesn't work in the first place, What GPU do you got?

**Comment by K900** [comment]
7900XTX and integrated. I assume it's failing to get metrics from the integrated, as it's normally unused.

**Comment by K900** [comment]
Master works now, thanks :)
