### ISSUE TITLE
Crash when resuming from suspend

### ISSUE THREAD

**Issue by K900** [Rem0o/FanControl.ADLX#47]
Another day, another segfault...

```
Application: FanControl.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at ADLXWrapper.Bindings.ADLXPINVOKE.IADLXInterface_Release(System.Runtime.InteropServices.HandleRef)
   at ADLXWrapper.Bindings.ADLXPINVOKE.IADLXInterface_Release(System.Runtime.InteropServices.HandleRef)
   at ADLXWrapper.Bindings.IADLXInterface.Release()
   at ADLXWrapper.ADLXInterfaceQueryWrapper`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Dispose()
   at FanControl.ADLX.ADLXPlugin+<>c.<DisposeAll>b__20_0(ADLXWrapper.ManualFanTuning)
   at System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ForEach(System.Action`1<System.__Canon>)
   at FanControl.ADLX.ADLXPlugin.DisposeAll()
   at FanControl.ADLX.ADLXPlugin.Close()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Close()
   at FanControl.Domain.ComputerAccessLayer.Close()
   at FanControl.Domain.ComputerAccessLayer+<>c__DisplayClass11_0+<<TryRefresh>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[FanControl.Domain.ComputerAccessLayer+<>c__DisplayClass11_0+<<TryRefresh>b__0>d, FanControl.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<<TryRefresh>b__0>d ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[FanControl.Domain.ComputerAccessLayer+<>c__DisplayClass11_0+<<TryRefresh>b__0>d, FanControl.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<<TryRefresh>b__0>d ByRef)
   at FanControl.Domain.ComputerAccessLayer+<>c__DisplayClass11_0.<TryRefresh>b__0()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

Not really sure what's going on here, refcounting issue possibly?

**Comment by Rem0o** [comment]
This one always happen when resuming from sleep it seems like. When resuming from sleep, the app does a refresh, and that refresh fails, as if some reference was lost. A refresh = Close() => Initialise() => Load() of the plugin.  It fails on the close. 
However, refreshing over and over in any other scenario that from a sleep resume, doing all kind of manipulation, it won't cause this. 

On my own computer it doesn't happen. I can't figure out why it does this on some computers. Maybe it has to do with the type of S1/S2/S3 sleep which messes with something.

**Comment by K900** [comment]
Interesting. It happens pretty consistently on mine. I can try running it under a debugger I guess?

**Comment by Rem0o** [comment]
Consistently, in what scenario ? From sleep or just a normal CTRL+R?

**Comment by K900** [comment]
Resuming from sleep, not _every_ time, but probably every other time or so? I wonder if it has something to do with the integrated graphics again.

**Comment by Rem0o** [comment]
If you can compile this code and debug it, the sequence for a refresh is:

Given the plugin has been Initialize() + Load().

[Sleep]

[Resume]
Close() => Initialize() => Load();

**Comment by Rem0o** [comment]
The fact it happens on "ADLXInterfaceQueryWrapper" means it happen in the ManualFanTuning/IADLXManualFanTuning class/interface.

**Comment by K900** [comment]
I can try debugging it tomorrow, but at a glance, I wonder if it has anything to do with destructor ordering...

**Comment by Rem0o** [comment]
@K900  

I replicated the ordering in the c/c++ samples in the ADLX repo. 

If that ordering was wrong, wouldn't the problem happen all the time?

**Comment by K900** [comment]
Yeah, you're probably right. I think I caught a cold though so I don't really have spoons to debug this today, but maybe in a few days..

**Comment by ahydronous** [comment]
Not sure if relevant, but I occasionally have

```
27-5-2024 13:39:17: ADLXWrapper.ADLXEception: Result: ADLX_ORPHAN_OBJECTS 
Couldn't terminate ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper.Dispose()
   at FanControl.ADLX.ADLXPlugin.DisposeAll()
   at FanControl.ADLX.ADLXPlugin.Close()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Close()
   at FanControl.Domain.ComputerAccessLayer.Close()
27-5-2024 22:09:56: ADLXWrapper.ADLXEception: Result: ADLX_ORPHAN_OBJECTS 
Couldn't terminate ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper.Dispose()
   at FanControl.ADLX.ADLXPlugin.DisposeAll()
   at FanControl.ADLX.ADLXPlugin.Close()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Close()
   at FanControl.Domain.ComputerAccessLayer.Close()
27-5-2024 23:37:00: ADLXWrapper.ADLXEception: Result: ADLX_ORPHAN_OBJECTS 
Couldn't terminate ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper.Dispose()
   at FanControl.ADLX.ADLXPlugin.DisposeAll()
   at FanControl.ADLX.ADLXPlugin.Close()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Close()
   at FanControl.Domain.ComputerAccessLayer.Close()

```

in my logs, because of suspending

**Comment by K900** [comment]
OK, so I got it to crash, and it's trying to release a null pointer: 
![image](https://github.com/Rem0o/FanControl.ADLX/assets/386765/64373de4-7ef7-492b-a66c-08cd30fd1407)

I'm not entirely sure how this is happening, because the only write to `swigCPtr` happens in `Dispose`, which should not be called at this point?

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.ADLX/assets/14118956/13b503a0-c08b-4329-aaf8-2e834ce06448)
Indeed, dispose is called after both the interface and manualfantuning are released.

Is your breakpoint/crash happening in that method at the release() ?

**Comment by K900** [comment]
![image](https://github.com/Rem0o/FanControl.ADLX/assets/386765/027fa6b7-4880-4a83-8ae3-308bb37b57e0)

Oh no. Is the compiler reordering these?

**Comment by K900** [comment]
I can upload a dump if you want to poke it yourself.

**Comment by Rem0o** [comment]
Update:

Found a non-checked ADLX_RESULT again here:
https://github.com/Rem0o/ADLX/blob/68b6d4b5ac7a7408048331123642b723d36685aa/Samples/csharp/ADLXWrapper/ManualFanTuning.cs#L20

Maybe somehow it failed there in the first place and then we try to release it afterwards?

As for your compiler reordering, are you up to date ? That order was changed very recently.

**Comment by K900** [comment]
No, this is ~two day old master. I don't see the exact commit hash in the version info, but the mtime is 2024-05-26 19:24 UTC.

**Comment by K900** [comment]
Sorry, I'm still pretty sick, so I'm going to bed. The dump is here: https://static.0upti.me/FanControl.dmp , have fun

**Comment by K900** [comment]
OK, I've updated to latest master, https://github.com/Rem0o/FanControl.ADLX/commit/d5f8fce3681c4a44d1c11c2b7c55ef573f953240 (mostly noting down for my own reference), and I'll just let it exist for a while because it seems to prefer to crash when I'm not actively trying to trigger it.

**Comment by K900** [comment]
Crashed again. I'm very much not a C# person, but reading https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern, it seems like the implementation of `Dispose` for `ADLXInterfaceQueryWrapper` might be wrong, because it tries to release other objects unconditionally?

**Comment by K900** [comment]
Well the obvious workaround would be to add a null check to `Release`, but I'm still not sure what is actually happening there...

**Comment by Rem0o** [comment]
If the ptr is 0x0000, it means the call to retrieve that ptr failed in the first place. 
![image](https://github.com/Rem0o/FanControl.ADLX/assets/14118956/2e26ea17-1378-4df8-bcbd-e120d9f02d73)

That ADLX_RESULT check was missing, will add.

**Comment by K900** [comment]
Trying with 3203fea7bf8df05d6a14576353e832f04120b7fd now.

**Comment by K900** [comment]
Crashed again, same signature. Something is definitely up with the destructor order.

**Comment by Rem0o** [comment]
V193 no longer crashes even though the orphan-object error is still present. 
V0.4 of the plugin reverts to the older method of getting the temperatures, which should eliminate the orphan_object exception.

If the issue reoccurs on V193+ with V0.4+ of the plugin, open back an issue.
