### ISSUE TITLE
ADXL_FAIL

### ISSUE THREAD

**Issue by AlexLamond** [Rem0o/FanControl.ADLX#5]
Installed as described, but the steps were kind of unclear. Getting the following when starting up Fan Control

```
01/03/2023 18:57:08: ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at FanControl.ADLX.ADLXPlugin.Initialize() in C:\projects\fancontrol-adlx\ADLXPlugin.cs:line 53
01/03/2023 18:57:08: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FanControl.ADLX.ADLXPlugin.Close() in C:\projects\fancontrol-adlx\ADLXPlugin.cs:line 37
   at FanControl.ADLX.ADLXPlugin.Initialize() in C:\projects\fancontrol-adlx\ADLXPlugin.cs:line 78
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
01/03/2023 18:57:10: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FanControl.ADLX.ADLXPlugin.Close() in C:\projects\fancontrol-adlx\ADLXPlugin.cs:line 37
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Close()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass14_0.<<TryRefresh>b__0>d.MoveNext()
01/03/2023 18:57:10: Initialization failed.
```

GPU: Radeon RX 6700 XT
Driver Version: 22.20.27.06

**Comment by Rem0o** [comment]
RDNA 3 gpus only AFAIK.
