### ISSUE TITLE
FanControl causes Internal Scheduler to Crash (resulting on a hard-crash)

### ISSUE THREAD

**Issue by ovflowd** [Rem0o/FanControl.ADLX#55]
I've been seeing `FanControl` somehow (supposedly) causing the PC to crash (almost every time when resuming from sleep).

### Example MiniDump

<details>
<summary>Details</summary>

```log
nt!KeBugCheckEx:
fffff801`81814f80 48894c2408      mov     qword ptr [rsp+8],rcx ss:0018:fffff801`85b94f90=0000000000000119

VIDEO_SCHEDULER_INTERNAL_ERROR (119)
The video scheduler has detected that fatal violation has occurred. This resulted
in a condition that video scheduler can no longer progress. Any other values after
parameter 1 must be individually examined according to the subtype.
Arguments:
Arg1: 0000000000000005, The subtype of the BugCheck:
Arg2: ffff968f8087c000
Arg3: ffff968f80949820
Arg4: 000000000002373f

Debugging Details:

AULTING_THREAD:  ffff968f8763c080

BLACKBOXBSD: 1 (!blackboxbsd)


BLACKBOXNTFS: 1 (!blackboxntfs)


BLACKBOXPNP: 1 (!blackboxpnp)


BLACKBOXWINLOGON: 1

CUSTOMER_CRASH_COUNT:  1

PROCESS_NAME:  FanControl.exe

STACK_TEXT:  
fffff801`85b94f88 fffff801`86ed5745     : 00000000`00000119 00000000`00000005 ffff968f`8087c000 ffff968f`80949820 : nt!KeBugCheckEx
fffff801`85b94f90 fffff801`fbd6afdb     : 00000000`00000006 ffff968f`74ffb300 ffff968f`74ffb308 ffff968f`74ffb310 : watchdog!WdLogSingleEntry5+0x3c05
fffff801`85b95040 fffff801`fbd5528d     : ffff968f`8087a000 ffff968f`8087c000 fffff801`85b95240 ffff968f`8087c000 : dxgmms2!VidSchiProcessIsrFaultedPacket+0x25f
fffff801`85b950c0 fffff801`fbd3ea7d     : 00000000`0002373f 00000000`ffffffeb ffff968f`8087a000 ffff968f`803c04f8 : dxgmms2!VidSchDdiNotifyInterruptWorker+0x1666d
fffff801`85b95140 fffff801`86a4f784     : ffff968f`74ec2030 fffff801`e5a27110 fffff801`85b95310 fffff801`e5339581 : dxgmms2!VidSchDdiNotifyInterrupt+0xcd
fffff801`85b951a0 fffff801`e53841c0     : fffff801`e5a27110 ffff968f`7e9c8020 ffff968f`7e9c8020 fffff801`e5223fd8 : dxgkrnl!DxgNotifyInterruptCB+0x94
fffff801`85b95210 fffff801`e5a27110     : ffff968f`7e9c8020 ffff968f`7e9c8020 fffff801`e5223fd8 fffff801`85b95440 : amdkmdag+0x1641c0
fffff801`85b95218 ffff968f`7e9c8020     : ffff968f`7e9c8020 fffff801`e5223fd8 fffff801`85b95440 ffff968f`803c0398 : amdkmdag+0x807110
fffff801`85b95220 ffff968f`7e9c8020     : fffff801`e5223fd8 fffff801`85b95440 ffff968f`803c0398 00000000`00000009 : 0xffff968f`7e9c8020
fffff801`85b95228 fffff801`e5223fd8     : fffff801`85b95440 ffff968f`803c0398 00000000`00000009 00000000`0002373f : 0xffff968f`7e9c8020
fffff801`85b95230 fffff801`85b95440     : ffff968f`803c0398 00000000`00000009 00000000`0002373f ffffffff`ffffffff : amdkmdag+0x3fd8
fffff801`85b95238 ffff968f`803c0398     : 00000000`00000009 00000000`0002373f ffffffff`ffffffff ffffffff`00000000 : 0xfffff801`85b95440
fffff801`85b95240 00000000`00000009     : 00000000`0002373f ffffffff`ffffffff ffffffff`00000000 00000000`00000000 : 0xffff968f`803c0398
fffff801`85b95248 00000000`0002373f     : ffffffff`ffffffff ffffffff`00000000 00000000`00000000 00000000`2021d000 : 0x9
fffff801`85b95250 ffffffff`ffffffff     : ffffffff`00000000 00000000`00000000 00000000`2021d000 00000000`00000004 : 0x2373f
fffff801`85b95258 ffffffff`00000000     : 00000000`00000000 00000000`2021d000 00000000`00000004 00000000`00000000 : 0xffffffff`ffffffff
fffff801`85b95260 00000000`00000000     : 00000000`2021d000 00000000`00000004 00000000`00000000 ffff968f`6c7fcb00 : 0xffffffff`00000000

SYMBOL_NAME:  amdkmdag+1641c0

MODULE_NAME: amdkmdag

IMAGE_NAME:  amdkmdag.sys

STACK_COMMAND:  .process /r /p 0xffff968f88ea80c0; .thread 0xffff968f8763c080 ; kb

BUCKET_ID_FUNC_OFFSET:  1641c0

FAILURE_BUCKET_ID:  0x119_5_DRIVER_FAULTED_SYSTEM_COMMAND_amdkmdag!unknown_function

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {b1920cde-0b10-25de-235f-7e545107ab75}

Followup:     MachineOwner
```

</details>

### Logs from Fan Control (sample)

<details>
<summary>Details</summary>

```log
10/8/2024 1:10:10 AM: ADLX could not initialize or has no sensors.
10/8/2024 9:44:34 AM: Unhandled exception in FanControl v200.0.0.0
10/8/2024 9:44:34 AM: LogUnhandledException - System.TimeoutException: Operation timed out.
   at HidSharp.Platform.Windows.NativeMethods.OverlappedOperation(IntPtr ioHandle, IntPtr eventHandle, Int32 eventTimeout, IntPtr closeEventHandle, Boolean overlapResult, NativeOverlapped* overlapped, UInt32& bytesTransferred)
   at HidSharp.Platform.Windows.WinHidStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at LibreHardwareMonitor.Hardware.Controller.Nzxt.KrakenV3.FanSoftwareControlValueChanged(Control control)
   at LibreHardwareMonitor.Hardware.Control.set_SoftwareValue(Single value)
   at FanControl.Domain.Control.Update()
   at FanControl.ViewModels.ControlViewModel.UpdateControl()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location ---
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
10/10/2024 10:21:33 AM: ADLX plugin: ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper..ctor()
   at FanControl.ADLX.ADLXPlugin.Initialize()
10/10/2024 10:21:33 AM: Open - System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ADLX.ADLXPlugin.DisposeAll()
   at FanControl.ADLX.ADLXPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
10/10/2024 10:21:34 AM: ADLX plugin: ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper..ctor()
   at FanControl.ADLX.ADLXPlugin.Initialize()
10/10/2024 10:21:34 AM: Open - System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ADLX.ADLXPlugin.DisposeAll()
   at FanControl.ADLX.ADLXPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
10/10/2024 10:21:39 AM: ADLX plugin: ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper..ctor()
   at FanControl.ADLX.ADLXPlugin.Initialize()
10/10/2024 10:21:39 AM: Open - System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ADLX.ADLXPlugin.DisposeAll()
   at FanControl.ADLX.ADLXPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
10/10/2024 10:21:42 AM: ADLX could not initialize or has no sensors.
10/10/2024 10:24:27 AM: GetUpdateVersionInfo - System.Net.Http.HttpRequestException: No such host is known. (raw.githubusercontent.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at FanControl.Domain.UpdaterService.GetUpdateVersionInfo()
```

</details>

### Settings

![image](https://github.com/user-attachments/assets/ae70e8be-2362-4edf-9383-aa37163c856a)

![image](https://github.com/user-attachments/assets/7f174f19-c093-47fb-aca5-a60692a3c0a1)

**Comment by ovflowd** [comment]
I've noticed I'm on an older version. I'll try to upgrade first, remove the ADLX plugin and check if things are still OK.

**Comment by ovflowd** [comment]
Updating also did not resolve it, but apparently now the culprit of it is "system" -- maybe something else is at play here 🤔

**Comment by Rem0o** [comment]
FanControl.ADLX plugin is deprecated by the way, as it is now "built-in" with FanControl (ADLX wrapper in your screenshot).

**Comment by ovflowd** [comment]
> FanControl.ADLX plugin is deprecated by the way, as it is now "built-in" with FanControl (ADLX wrapper in your screenshot).  

Right, and I stated that in one of my comments. I already tested by updating the main program and removing the Plugin... issue still happens 🥹

**Comment by ovflowd** [comment]
I've noticed I opened this issue on FanControl.ADLX rather than FanControl.Releases, @Rem0o would you mind transferring the issue?
